name: lint

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  deployment_pipeline_job:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: actions/setup-node@v1
        with:
          node-version: "14.17.1"
      - name: install npm dependencies
        run: npm install
      - name: lint js files
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e test
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: deploy
        if: ${{ github.event_name == 'push' }}
        env:
          COMMITS_STRING: ${{ github.event.commits }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fstack-pokedex"
          heroku_email: "ericmiranda7@gmail.com"
          healthcheck: "https://fstack-pokedex.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
      - uses: actions/checkout@v2
      - name: Bump version and tag release
        if: github.event_name == 'push' && !contains(${{ env.COMMITS_STRING }}, '#skip')
        run: echo 'B4 ENV $'
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          COMMITS_STRING: ${{ join(github.event.commits) }}
